[package]
name = "limbo_alloc"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3"
allocator-api2 = "0.2.21"

[dev-dependencies]
criterion = { version = "0.5", features = [
    "html_reports",
    "async",
    "async_futures",
] }

[[bench]]
name = "bench"
harness = false
